<a href="https://colab.research.google.com/github/GneccoFR/ColabExercises/blob/Numpy-Exercises/ColabExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
#This is a series of exercises written in Python

#First Exercise:
print("Asignation exercise:")
x='spam'
y=' and eggs'
print(x+y)
print()

#Second Exercise:
print("Numpy exercise: Import")
import numpy as np
print()

#Third Exercise:
print("Numpy exercise: One Dimensional Arrays")
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)
print()

#Fourth Exercise:
print("Numpy exercise: Two Dimensional Arrays:")
two_dimensional_array = np.array([[6, 5, 8], [11, 7, 1], [4, 8, 7]])
print(two_dimensional_array)
print()

#Fifth Exercise:
print("Numpy exercise: Populate an Array with a sequence:")
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)
print()

#Sixth Exercise:
print("Numpy exercise: Populate an Array with random integer numbers:")
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(10,))
print(random_integers_between_50_and_100)
print()

#Seventh Exercise:
print("Numpy exercise: Populate an Array with random float values:")
random_floats_between_0_and_1 = np.random.random((10,))
print(random_floats_between_0_and_1)
print()

#Eighth Exercise:
print("Numpy exercise: Using broadcasting on Numpy Operands(+):")
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)
print()

#Ninth Exercise:
print("Numpy exercise: Using broadcasting on Numpy Operands(*):")
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)
print()

Asignation exercise:
spam and eggs

Numpy exercise: Import

Numpy exercise: One Dimensional Arrays
[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]

Numpy exercise: Two Dimensional Arrays:
[[ 6  5  8]
 [11  7  1]
 [ 4  8  7]]

Numpy exercise: Populate an Array with a sequence:
[ 5  6  7  8  9 10 11]

Numpy exercise: Populate an Array with random integer numbers:
[ 76  79  80  58  54 100  83  58  72  53]

Numpy exercise: Populate an Array with random float values:
[0.76581502 0.90977403 0.99188945 0.64813482 0.86280483 0.22723693
 0.41251295 0.43985361 0.92170118 0.16656307]

Numpy exercise: Using broadcasting on Numpy Operands(+):
[2.76581502 2.90977403 2.99188945 2.64813482 2.86280483 2.22723693
 2.41251295 2.43985361 2.92170118 2.16656307]

Numpy exercise: Using broadcasting on Numpy Operands(*):
[228 237 240 174 162 300 249 174 216 159]

