<a href="https://colab.research.google.com/github/GneccoFR/ColabExercises/blob/Numpy-Exercises/ColabExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#This is a series of exercises written in Python

#First Exercise:
print("Asignation exercise:")
x='spam'
y=' and eggs'
print(x+y, '\n')

#Second Exercise:
print("Numpy exercise: Import \n")
import numpy as np

#Third Exercise:
print("Numpy exercise: One Dimensional Arrays")
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array, '\n')

#Fourth Exercise:
print("Numpy exercise: Two Dimensional Arrays:")
two_dimensional_array = np.array([[6, 5, 8], [11, 7, 1], [4, 8, 7]])
print(two_dimensional_array, '\n')

#Fifth Exercise:
print("Numpy exercise: Populate an Array with a sequence:")
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers, '\n')

#Sixth Exercise:
print("Numpy exercise: Populate an Array with random integer numbers:")
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(10,))
print(random_integers_between_50_and_100, '\n')

#Seventh Exercise:
print("Numpy exercise: Populate an Array with random float values:")
random_floats_between_0_and_1 = np.random.random((10,))
print(random_floats_between_0_and_1, '\n')

#Eighth Exercise:
print("Numpy exercise: Using broadcasting on Numpy Operands(+):")
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3, '\n')

#Ninth Exercise:
print("Numpy exercise: Using broadcasting on Numpy Operands(*):")
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300, '\n')

#Tenth Exercise:
print("Numpy exercise: Creating a Linear Dataset:")
feature = np.arange(6, 21)
print(feature)
label = (feature *3) + 4
print(label, '\n')

#Tenth Exercise:
print("Numpy exercise: Adding Noise to the Dataset: \n")
noise = (np.random.random([15]) * 4) - 2
print('Noise:')
print(noise, '\n')
label = label + noise
print('Label:')
print(label)

Asignation exercise:
spam and eggs 

Numpy exercise: Import 

Numpy exercise: One Dimensional Arrays
[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5] 

Numpy exercise: Two Dimensional Arrays:
[[ 6  5  8]
 [11  7  1]
 [ 4  8  7]] 

Numpy exercise: Populate an Array with a sequence:
[ 5  6  7  8  9 10 11] 

Numpy exercise: Populate an Array with random integer numbers:
[74 76 97 53 94 56 50 89 69 93] 

Numpy exercise: Populate an Array with random float values:
[0.48065006 0.8150095  0.49492351 0.62921067 0.88715775 0.38506146
 0.5539791  0.84068009 0.13716456 0.88342241] 

Numpy exercise: Using broadcasting on Numpy Operands(+):
[2.48065006 2.8150095  2.49492351 2.62921067 2.88715775 2.38506146
 2.5539791  2.84068009 2.13716456 2.88342241] 

Numpy exercise: Using broadcasting on Numpy Operands(*):
[222 228 291 159 282 168 150 267 207 279] 

Numpy exercise: Creating a Linear Dataset:
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64] 

Numpy exercise: Adding N