<a href="https://colab.research.google.com/github/GneccoFR/ColabExercises/blob/Numpy-Exercises/ColabExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
#This is a series of exercises written in Python

#First Exercise:
print("Asignation exercise:")
x='spam'
y=' and eggs'
print(x+y)
print()

#Second Exercise:
print("Numpy exercise: Import")
import numpy as np
print()

#Third Exercise:
print("Numpy exercise: One Dimensional Arrays")
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)
print()

#Fourth Exercise:
print("Numpy exercise: Two Dimensional Arrays:")
two_dimensional_array = np.array([[6, 5, 8], [11, 7, 1], [4, 8, 7]])
print(two_dimensional_array)
print()

#Fifth Exercise:
print("Numpy exercise: Populate an Array with a sequence:")
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

Asignation exercise:
spam and eggs

Numpy exercise: Import

Numpy exercise: One Dimensional Arrays
[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]

Numpy exercise: Two Dimensional Arrays:
[[ 6  5  8]
 [11  7  1]
 [ 4  8  7]]

Numpy exercise: Populate an Array with a sequence:
[ 5  6  7  8  9 10 11]
