<a href="https://colab.research.google.com/github/GneccoFR/ColabExercises/blob/Numpy-Exercises/ColabExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
#This is a series of exercises written in Python

#First Exercise:
print("Asignation exercise:")
x='spam'
y=' and eggs'
print(x+y)
print()

#Second Exercise:
print("Numpy exercise: Import")
import numpy as np
print()

#Third Exercise:
print("Numpy exercise: One Dimensional Arrays")
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)
print()

#Fourth Exercise:
print("Numpy exercise: Two Dimensional Arrays:")
two_dimensional_array = np.array([[6, 5, 8], [11, 7, 1], [4, 8, 7]])
print(two_dimensional_array)
print()

#Fifth Exercise:
print("Numpy exercise: Populate an Array with a sequence:")
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)
print()

#Sixth Exercise:
print("Numpy exercise: Populate an Array with random integer numbers:")
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(10,))
print(random_integers_between_50_and_100)
print()

#Seventh Exercise:
print("Numpy exercise: Populate an Array with random float values:")
random_floats_between_0_and_1 = np.random.random((10,))
print(random_floats_between_0_and_1)
print()

#Eighth Exercise:
print("Numpy exercise: Using broadcasting on Numpy Operands(+):")
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)
print()

#Ninth Exercise:
print("Numpy exercise: Using broadcasting on Numpy Operands(*):")
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)
print()

#Tenth Exercise:
print("Numpy exercise: Creating a Linear Dataset:")
feature = np.arange(6, 21)
print(feature)
label = (feature *3) + 4
print(label)
print()

#Tenth Exercise:
print("Numpy exercise: Adding Noise to the Dataset:")
noise = (np.random.random([15]) * 4) - 2
print('Noise:')
print(noise)
label = label + noise
print('Label:')
print(label)

Asignation exercise:
spam and eggs

Numpy exercise: Import

Numpy exercise: One Dimensional Arrays
[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]

Numpy exercise: Two Dimensional Arrays:
[[ 6  5  8]
 [11  7  1]
 [ 4  8  7]]

Numpy exercise: Populate an Array with a sequence:
[ 5  6  7  8  9 10 11]

Numpy exercise: Populate an Array with random integer numbers:
[69 87 98 59 68 96 53 55 65 76]

Numpy exercise: Populate an Array with random float values:
[0.72996729 0.40691752 0.12382756 0.24847523 0.25496297 0.79013375
 0.34304411 0.19699985 0.86073173 0.10056611]

Numpy exercise: Using broadcasting on Numpy Operands(+):
[2.72996729 2.40691752 2.12382756 2.24847523 2.25496297 2.79013375
 2.34304411 2.19699985 2.86073173 2.10056611]

Numpy exercise: Using broadcasting on Numpy Operands(*):
[207 261 294 177 204 288 159 165 195 228]

Numpy exercise: Creating a Linear Dataset:
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]

Numpy exercise: Adding Noise to th